name: Deploy pages
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install dependencies
        run: cd slides && yarn install
      - name: Install slidev
        run: cd slides && yarn add -D @slidev/cli
      - name: Build
        run: cd slides && yarn slidev build --base talk-xstate-at-bdxio-2022
      - name: Deploy pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: slides/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
